### PR TITLE
Remove extra db file

### PR DESCRIPTION
**Pull request by aturkewi**
@PeterBell @dylan-okeefe @pletcher

### CODE REVIEW

**Comment by PeterBell** [comment]
Hey @aturkewi just to clarify, what's going on here? Looks like @joshuabamboo created a commit in Nov of '15 called "include solution" on master branch which added all the following changes: https://github.com/learn-co-curriculum/Active-Record-Association-Methods/commit/45fe80d85015050eddaaa8c52a06db486ccd9d5b and it looks like this PR is just removing the migrations. Is this what we want? Do we want to lose _all_ of the changes in that commit? Do we _want_ to get rid of the migrations? Not looked deeply through the lab - any way you could just briefly share what's broken and why this is the right fix? It'll be easier to put :eyes: on then. Thanks!!!

**Comment by pletcher** [comment]
As in #14, seconding @PeterBell -- with a bit more description so that we can see what happened when we come back to this, this'll be good to go!

**Comment by AnnJohn** [comment]
@aturkewi assigning this PR back to you

**Comment by aturkewi** [comment]
Hey @AnnJohn, what would be best for me to do with this? I had already updated the commit message per Chuck's request and that was accepted for the solution branch. Is there anything else that I should be updating for this?

**Comment by pletcher** [comment]
I think it was just for the merge :) I'll go ahead and merge it in -- thanks!

**Pull request merged**
