### PR TITLE
Remove extra migrate file

### PR DESCRIPTION
**Pull request by aturkewi**
@PeterBell @dylan-okeefe @pletcher

### CODE REVIEW

**Comment by PeterBell** [comment]
Hey @aturkewi again, could you just add a little more of a description of what's going on, why removing the migration, etc? Not saying it isn't right thing - just trying to have some more context so we can more quickly add :eyes: to this . . .

**Comment by pletcher** [comment]
Seconding @PeterBell, a bit more description would be :a:+. (`git commit --amend` [enter new commit message] `git push -f` (fine to force push to your branch)

Also, how did this happen? This is kind of zany :D

But after that, this LGTM!

**Comment by aturkewi** [comment]
@pletcher @PeterBell Updated the commit message for the master and solution branch. Is this more what you're looking for?

**Comment by pletcher** [comment]
I dig it.

**Comment by PeterBell** [comment]
Awesome - LGTM @aturkewi gonna :ship: it

**Comment by aturkewi** [comment]
Thanks for helping me get the hang of this workflow guys !

**Comment by PeterBell** [comment]
And also, @aturkewi just so you know, you can commit --amend to add more description to the commit message as @pletcher said. Benefit of that is all your notes are available in the Git repo. However if you're using GitHub (or a similar service) it's also cool just to add a comment to the PR like this one to better explain what's going on. Both are reasonable workflows. The goal is just to make sure that whoever needs to put :eyes: on your patch can do so in the minimum time possible while still understanding context and having a good shot of catching any logical fallacies in your reasoning, typos in your code, etc.

**Comment by PeterBell** [comment]
The workflow is a little stricter for production code where I'd want to download and run the tests to make sure there were no regressions, but for curriculum a quicker skim is sometimes OK . . .

**Pull request merged**
